baseURL = "https://nokola.github.io/"
languageCode = "en-us"
title = "You Had Me At 'Hello World'"
theme = "ananke"

[params]
    graphCommentId = "nokola-blog"
    subtitle = "Design, Coding, and Special Effects"
    featured_image = "tree1.jpg"
    body_classes = "baskerville  bg-near-white"