baseURL = "https://systemfailure.io/"
languageCode = "en-us"
title = "System Failure"
theme = "ananke"

[params]
    graphCommentId = "nokola-blog"
    subtitle = "Software for humans"
    featured_image = "header/tree1.jpg"
    body_classes = "body-font"
    date_format = "Jan 2, 2006"

# https://gohugo.io/content-management/formats/#blackfriday-extensions
[blackfriday]
    extensions = ["hardLineBreak", "noEmptyLineBeforeBlock"]