baseURL = "https://nokola.github.io/"
languageCode = "en-us"
title = "You Had Me At 'Hello World'"
theme = "ananke"

[params]
    graphCommentId = "nokola-blog"
    subtitle = "Design, coding, and special effects"
    featured_image = "header/tree1.jpg"
    body_classes = "baskerville  bg-near-white"