baseURL = "https://nokola.github.io/"
languageCode = "en-us"
title = "You Had Me At 'Hello World'"
theme = "ananke"

[params]
    graphCommentId = "nokola-blog"
    subtitle = "Design, coding, and special effects"
    featured_image = "header/tree1.jpg"
    body_classes = "body-font bg-white"
    date_format = "2006, Jan 2"