baseURL = "https://systemfailure.io/"
languageCode = "en-us"
title = "System Failure"
theme = "ananke"
pygmentsCodeFences = true

[params]
subtitle = "Nokola's handwritten blog on software and humans."
featured_image = "header/tree1.jpg"
body_classes = "body-font"
date_format = "Jan 2, 2006"

# https://gohugo.io/content-management/formats/#blackfriday-extensions
[blackfriday]
extensions = ["hardLineBreak", "noEmptyLineBeforeBlock"]
