baseURL = "https://systemfailure.io/"
languageCode = "en-us"
title = "SYSTEM FAILURE"
theme = "ananke"

[params]
    graphCommentId = "nokola-blog"
    subtitle = "Working with humans. Product care. Coding."
    featured_image = "header/tree1.jpg"
    body_classes = "body-font"
    date_format = "Jan 2, 2006"