name: Publish Hugo Blog on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.59.0
          TARGET_REPO: nokola/nokola.github.io
          TOKEN: ${{ secrets.NOKOLA_BLOG_WRITE_KEY }}
