name: Publish blog

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - uses: jsumners/gh-action-hugo-deploy@v1.0.0
      with:
        hugo_args: --gc --minify
        destination_repo: nokola/nokola.github.io
        destination_token: ${{ secrets.NOKOLA_BLOG_WRITE_KEY }}
