name: Publish Hugo Blog on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: nokola/nokola.github.io
          destination_token: ${{ secrets.NOKOLA_BLOG_WRITE_KEY }}
