name: Publish Hugo Blog on push to master

on:
  push:
    branches:
      - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: nokola/blog@master
      env:
        GIT_DEPLOY_KEY: ${{ secrets.NOKOLA_BLOG_WRITE_KEY }}
        HUGO_VERSION: "0.59"
        WEBSITE_GIT: "git@github.com:nokola/nokola.github.io.git"
        WEBSITE_DIR: "public"
