name: Publish blog

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: build
      uses: github-actions-x/hugo@master

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.NOKOLA_BLOG_WRITE_KEY }}
        INPUT_KEEPFILES: true
        EXTERNAL_REPOSITORY: nokola/nokola.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
